/*
 * MarvelComics.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/12/2016
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using MarvelComics.PCL;

namespace MarvelComics.PCL.Models
{
    public class Character : INotifyPropertyChanged 
    {
        // These fields hold the values for the public properties.
        private ComicList comics;
        private string description;
        private EventList events;
        private int id;
        private DateTime modified;
        private string name;
        private string resourceURI;
        private SeriesList series;
        private StoryList stories;
        private Thumbnail thumbnail;
        private List<Url> urls;

        /// <summary>
        /// A resource list containing comics which feature this character.
        /// </summary>
        [JsonProperty("comics")]
        public ComicList Comics 
        { 
            get 
            {
                return this.comics; 
            } 
            set 
            {
                this.comics = value;
                onPropertyChanged("Comics");
            }
        }

        /// <summary>
        /// A short bio or description of the character.
        /// </summary>
        [JsonProperty("description")]
        public string Description 
        { 
            get 
            {
                return this.description; 
            } 
            set 
            {
                this.description = value;
                onPropertyChanged("Description");
            }
        }

        /// <summary>
        /// A resource list of events in which this character appears.
        /// </summary>
        [JsonProperty("events")]
        public EventList Events 
        { 
            get 
            {
                return this.events; 
            } 
            set 
            {
                this.events = value;
                onPropertyChanged("Events");
            }
        }

        /// <summary>
        /// The unique ID of the character resource.
        /// </summary>
        [JsonProperty("id")]
        public int Id 
        { 
            get 
            {
                return this.id; 
            } 
            set 
            {
                this.id = value;
                onPropertyChanged("Id");
            }
        }

        /// <summary>
        /// The date the resource was most recently modified.
        /// </summary>
        [JsonProperty("modified")]
        public DateTime Modified 
        { 
            get 
            {
                return this.modified; 
            } 
            set 
            {
                this.modified = value;
                onPropertyChanged("Modified");
            }
        }

        /// <summary>
        /// The name of the character.
        /// </summary>
        [JsonProperty("name")]
        public string Name 
        { 
            get 
            {
                return this.name; 
            } 
            set 
            {
                this.name = value;
                onPropertyChanged("Name");
            }
        }

        /// <summary>
        /// The canonical URL identifier for this resource.
        /// </summary>
        [JsonProperty("resourceURI")]
        public string ResourceURI 
        { 
            get 
            {
                return this.resourceURI; 
            } 
            set 
            {
                this.resourceURI = value;
                onPropertyChanged("ResourceURI");
            }
        }

        /// <summary>
        /// A resource list of series in which this character appears.
        /// </summary>
        [JsonProperty("series")]
        public SeriesList Series 
        { 
            get 
            {
                return this.series; 
            } 
            set 
            {
                this.series = value;
                onPropertyChanged("Series");
            }
        }

        /// <summary>
        /// A resource list of stories in which this character appears.
        /// </summary>
        [JsonProperty("stories")]
        public StoryList Stories 
        { 
            get 
            {
                return this.stories; 
            } 
            set 
            {
                this.stories = value;
                onPropertyChanged("Stories");
            }
        }

        /// <summary>
        /// The representative image for this character.
        /// </summary>
        [JsonProperty("thumbnail")]
        public Thumbnail Thumbnail 
        { 
            get 
            {
                return this.thumbnail; 
            } 
            set 
            {
                this.thumbnail = value;
                onPropertyChanged("Thumbnail");
            }
        }

        /// <summary>
        /// A set of public web site URLs for the resource.
        /// </summary>
        [JsonProperty("urls")]
        public List<Url> Urls 
        { 
            get 
            {
                return this.urls; 
            } 
            set 
            {
                this.urls = value;
                onPropertyChanged("Urls");
            }
        }

        /// <summary>
        /// Property changed event for observer pattern
        /// </summary>
        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Raises event when a property is changed
        /// </summary>
        /// <param name="propertyName">Name of the changed property</param>
        protected void onPropertyChanged(String propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
} 