/*
 * MarvelComics.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/12/2016
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using MarvelComics.PCL;

namespace MarvelComics.PCL.Models
{
    public class Creator : INotifyPropertyChanged 
    {
        // These fields hold the values for the public properties.
        private ComicList comics;
        private EventList events;
        private string firstName;
        private string fullName;
        private int id;
        private string lastName;
        private string middleName;
        private DateTime modified;
        private string resourceURI;
        private SeriesList series;
        private StoryList stories;
        private string suffix;
        private Thumbnail thumbnail;
        private List<Url> urls;

        /// <summary>
        /// A resource list containing the comics which feature work by this creator.
        /// </summary>
        [JsonProperty("comics")]
        public ComicList Comics 
        { 
            get 
            {
                return this.comics; 
            } 
            set 
            {
                this.comics = value;
                onPropertyChanged("Comics");
            }
        }

        /// <summary>
        /// A resource list containing the events which feature work by this creator.
        /// </summary>
        [JsonProperty("events")]
        public EventList Events 
        { 
            get 
            {
                return this.events; 
            } 
            set 
            {
                this.events = value;
                onPropertyChanged("Events");
            }
        }

        /// <summary>
        /// The first name of the creator.
        /// </summary>
        [JsonProperty("firstName")]
        public string FirstName 
        { 
            get 
            {
                return this.firstName; 
            } 
            set 
            {
                this.firstName = value;
                onPropertyChanged("FirstName");
            }
        }

        /// <summary>
        /// The full name of the creator (a space-separated concatenation of the above four fields).
        /// </summary>
        [JsonProperty("fullName")]
        public string FullName 
        { 
            get 
            {
                return this.fullName; 
            } 
            set 
            {
                this.fullName = value;
                onPropertyChanged("FullName");
            }
        }

        /// <summary>
        /// The unique ID of the creator resource.
        /// </summary>
        [JsonProperty("id")]
        public int Id 
        { 
            get 
            {
                return this.id; 
            } 
            set 
            {
                this.id = value;
                onPropertyChanged("Id");
            }
        }

        /// <summary>
        /// The last name of the creator.
        /// </summary>
        [JsonProperty("lastName")]
        public string LastName 
        { 
            get 
            {
                return this.lastName; 
            } 
            set 
            {
                this.lastName = value;
                onPropertyChanged("LastName");
            }
        }

        /// <summary>
        /// The middle name of the creator.
        /// </summary>
        [JsonProperty("middleName")]
        public string MiddleName 
        { 
            get 
            {
                return this.middleName; 
            } 
            set 
            {
                this.middleName = value;
                onPropertyChanged("MiddleName");
            }
        }

        /// <summary>
        /// The date the resource was most recently modified.
        /// </summary>
        [JsonProperty("modified")]
        public DateTime Modified 
        { 
            get 
            {
                return this.modified; 
            } 
            set 
            {
                this.modified = value;
                onPropertyChanged("Modified");
            }
        }

        /// <summary>
        /// The canonical URL identifier for this resource.
        /// </summary>
        [JsonProperty("resourceURI")]
        public string ResourceURI 
        { 
            get 
            {
                return this.resourceURI; 
            } 
            set 
            {
                this.resourceURI = value;
                onPropertyChanged("ResourceURI");
            }
        }

        /// <summary>
        /// A resource list containing the series which feature work by this creator.
        /// </summary>
        [JsonProperty("series")]
        public SeriesList Series 
        { 
            get 
            {
                return this.series; 
            } 
            set 
            {
                this.series = value;
                onPropertyChanged("Series");
            }
        }

        /// <summary>
        /// A resource list containing the stories which feature work by this creator.
        /// </summary>
        [JsonProperty("stories")]
        public StoryList Stories 
        { 
            get 
            {
                return this.stories; 
            } 
            set 
            {
                this.stories = value;
                onPropertyChanged("Stories");
            }
        }

        /// <summary>
        /// The suffix or honorific for the creator.
        /// </summary>
        [JsonProperty("suffix")]
        public string Suffix 
        { 
            get 
            {
                return this.suffix; 
            } 
            set 
            {
                this.suffix = value;
                onPropertyChanged("Suffix");
            }
        }

        /// <summary>
        /// The representative image for this creator.
        /// </summary>
        [JsonProperty("thumbnail")]
        public Thumbnail Thumbnail 
        { 
            get 
            {
                return this.thumbnail; 
            } 
            set 
            {
                this.thumbnail = value;
                onPropertyChanged("Thumbnail");
            }
        }

        /// <summary>
        /// A set of public web site URLs for the resource.
        /// </summary>
        [JsonProperty("urls")]
        public List<Url> Urls 
        { 
            get 
            {
                return this.urls; 
            } 
            set 
            {
                this.urls = value;
                onPropertyChanged("Urls");
            }
        }

        /// <summary>
        /// Property changed event for observer pattern
        /// </summary>
        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Raises event when a property is changed
        /// </summary>
        /// <param name="propertyName">Name of the changed property</param>
        protected void onPropertyChanged(String propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
} 