/*
 * MarvelComics.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/12/2016
 */
using System;
using System.Linq;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using MarvelComics.PCL;

namespace MarvelComics.PCL.Models
{
    [JsonConverter(typeof(StringValuedEnumConverter))]
    public enum DateDescriptorEnum
    {
        LASTWEEK, //TODO: Write general description for this method
        NEXTWEEK, //TODO: Write general description for this method
        THISMONTH, //TODO: Write general description for this method
        THISWEEK, //TODO: Write general description for this method
    }

    /// <summary>
    /// Helper for the enum type DateDescriptorEnum
    /// </summary>
    public static class DateDescriptorEnumHelper
    {
        //string values corresponding the enum elements
        private static List<string> stringValues = new List<string> { "lastWeek", "nextWeek", "thisMonth", "thisWeek" };

        /// <summary>
        /// Converts a DateDescriptorEnum value to a corresponding string value
        /// </summary>
        /// <param name="enumValue">The DateDescriptorEnum value to convert</param>
        /// <returns>The representative string value</returns>
        public static string ToValue(DateDescriptorEnum enumValue)
        {
            switch(enumValue)
            {
                //only valid enum elements can be used
                //this is necessary to avoid errors
                case DateDescriptorEnum.LASTWEEK:
                case DateDescriptorEnum.NEXTWEEK:
                case DateDescriptorEnum.THISMONTH:
                case DateDescriptorEnum.THISWEEK:
                    return stringValues[(int)enumValue];

                //an invalid enum value was requested
                default:
                    return null;
            }
        }

        /// <summary>
        /// Convert a list of DateDescriptorEnum values to a list of strings
        /// </summary>
        /// <param name="enumValues">The list of DateDescriptorEnum values to convert</param>
        /// <returns>The list of representative string values</returns>
        public static List<string> ToValue(List<DateDescriptorEnum> enumValues)
        {
            if (null == enumValues)
                return null;

            return enumValues.Select(eVal => ToValue(eVal)).ToList();
        }

        /// <summary>
        /// Converts a string value into DateDescriptorEnum value
        /// </summary>
        /// <param name="value">The string value to parse</param>
        /// <returns>The parsed DateDescriptorEnum value</returns>
        public static DateDescriptorEnum ParseString(string value)
        {
            int index = stringValues.IndexOf(value);
            if(index < 0)
                throw new InvalidCastException(string.Format("Unable to cast value: {0} to type DateDescriptorEnum", value));

            return (DateDescriptorEnum) index;
        }
    }
} 