/*
 * MarvelComics.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/12/2016
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using MarvelComics.PCL;

namespace MarvelComics.PCL.Models
{
    public class Series : INotifyPropertyChanged 
    {
        // These fields hold the values for the public properties.
        private CharacterList characters;
        private ComicList comics;
        private CreatorList creators;
        private string description;
        private int endYear;
        private EventList events;
        private int id;
        private DateTime modified;
        private SeriesSummary next;
        private SeriesSummary previous;
        private string rating;
        private string resourceURI;
        private int startYear;
        private StoryList stories;
        private Thumbnail thumbnail;
        private string title;
        private List<Url> urls;

        /// <summary>
        /// A resource list containing characters which appear in comics in this series.
        /// </summary>
        [JsonProperty("characters")]
        public CharacterList Characters 
        { 
            get 
            {
                return this.characters; 
            } 
            set 
            {
                this.characters = value;
                onPropertyChanged("Characters");
            }
        }

        /// <summary>
        /// A resource list containing comics in this series.
        /// </summary>
        [JsonProperty("comics")]
        public ComicList Comics 
        { 
            get 
            {
                return this.comics; 
            } 
            set 
            {
                this.comics = value;
                onPropertyChanged("Comics");
            }
        }

        /// <summary>
        /// A resource list of creators whose work appears in comics in this series.
        /// </summary>
        [JsonProperty("creators")]
        public CreatorList Creators 
        { 
            get 
            {
                return this.creators; 
            } 
            set 
            {
                this.creators = value;
                onPropertyChanged("Creators");
            }
        }

        /// <summary>
        /// A description of the series.
        /// </summary>
        [JsonProperty("description")]
        public string Description 
        { 
            get 
            {
                return this.description; 
            } 
            set 
            {
                this.description = value;
                onPropertyChanged("Description");
            }
        }

        /// <summary>
        /// The last year of publication for the series (conventionally, 2099 for ongoing series) .
        /// </summary>
        [JsonProperty("endYear")]
        public int EndYear 
        { 
            get 
            {
                return this.endYear; 
            } 
            set 
            {
                this.endYear = value;
                onPropertyChanged("EndYear");
            }
        }

        /// <summary>
        /// A resource list containing events which take place in comics in this series.
        /// </summary>
        [JsonProperty("events")]
        public EventList Events 
        { 
            get 
            {
                return this.events; 
            } 
            set 
            {
                this.events = value;
                onPropertyChanged("Events");
            }
        }

        /// <summary>
        /// The unique ID of the series resource.
        /// </summary>
        [JsonProperty("id")]
        public int Id 
        { 
            get 
            {
                return this.id; 
            } 
            set 
            {
                this.id = value;
                onPropertyChanged("Id");
            }
        }

        /// <summary>
        /// The date the resource was most recently modified.
        /// </summary>
        [JsonProperty("modified")]
        public DateTime Modified 
        { 
            get 
            {
                return this.modified; 
            } 
            set 
            {
                this.modified = value;
                onPropertyChanged("Modified");
            }
        }

        /// <summary>
        /// A summary representation of the series which follows this series.
        /// </summary>
        [JsonProperty("next")]
        public SeriesSummary Next 
        { 
            get 
            {
                return this.next; 
            } 
            set 
            {
                this.next = value;
                onPropertyChanged("Next");
            }
        }

        /// <summary>
        /// A summary representation of the series which preceded this series.
        /// </summary>
        [JsonProperty("previous")]
        public SeriesSummary Previous 
        { 
            get 
            {
                return this.previous; 
            } 
            set 
            {
                this.previous = value;
                onPropertyChanged("Previous");
            }
        }

        /// <summary>
        /// The age-appropriateness rating for the series.
        /// </summary>
        [JsonProperty("rating")]
        public string Rating 
        { 
            get 
            {
                return this.rating; 
            } 
            set 
            {
                this.rating = value;
                onPropertyChanged("Rating");
            }
        }

        /// <summary>
        /// The canonical URL identifier for this resource.
        /// </summary>
        [JsonProperty("resourceURI")]
        public string ResourceURI 
        { 
            get 
            {
                return this.resourceURI; 
            } 
            set 
            {
                this.resourceURI = value;
                onPropertyChanged("ResourceURI");
            }
        }

        /// <summary>
        /// The first year of publication for the series.
        /// </summary>
        [JsonProperty("startYear")]
        public int StartYear 
        { 
            get 
            {
                return this.startYear; 
            } 
            set 
            {
                this.startYear = value;
                onPropertyChanged("StartYear");
            }
        }

        /// <summary>
        /// A resource list containing stories which occur in comics in this series.
        /// </summary>
        [JsonProperty("stories")]
        public StoryList Stories 
        { 
            get 
            {
                return this.stories; 
            } 
            set 
            {
                this.stories = value;
                onPropertyChanged("Stories");
            }
        }

        /// <summary>
        /// The representative image for this series.
        /// </summary>
        [JsonProperty("thumbnail")]
        public Thumbnail Thumbnail 
        { 
            get 
            {
                return this.thumbnail; 
            } 
            set 
            {
                this.thumbnail = value;
                onPropertyChanged("Thumbnail");
            }
        }

        /// <summary>
        /// The canonical title of the series.
        /// </summary>
        [JsonProperty("title")]
        public string Title 
        { 
            get 
            {
                return this.title; 
            } 
            set 
            {
                this.title = value;
                onPropertyChanged("Title");
            }
        }

        /// <summary>
        /// A set of public web site URLs for the resource.
        /// </summary>
        [JsonProperty("urls")]
        public List<Url> Urls 
        { 
            get 
            {
                return this.urls; 
            } 
            set 
            {
                this.urls = value;
                onPropertyChanged("Urls");
            }
        }

        /// <summary>
        /// Property changed event for observer pattern
        /// </summary>
        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Raises event when a property is changed
        /// </summary>
        /// <param name="propertyName">Name of the changed property</param>
        protected void onPropertyChanged(String propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
} 