/*
 * MarvelComics.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/12/2016
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using MarvelComics.PCL;

namespace MarvelComics.PCL.Models
{
    public class Story : INotifyPropertyChanged 
    {
        // These fields hold the values for the public properties.
        private CharacterList characters;
        private ComicList comics;
        private CreatorList creators;
        private string description;
        private EventList events;
        private int id;
        private DateTime modified;
        private ComicSummary originalissue;
        private string resourceURI;
        private SeriesList series;
        private Thumbnail thumbnail;
        private string title;
        private string type;

        /// <summary>
        /// A resource list of characters which appear in this story.
        /// </summary>
        [JsonProperty("characters")]
        public CharacterList Characters 
        { 
            get 
            {
                return this.characters; 
            } 
            set 
            {
                this.characters = value;
                onPropertyChanged("Characters");
            }
        }

        /// <summary>
        /// A resource list containing comics in which this story takes place.
        /// </summary>
        [JsonProperty("comics")]
        public ComicList Comics 
        { 
            get 
            {
                return this.comics; 
            } 
            set 
            {
                this.comics = value;
                onPropertyChanged("Comics");
            }
        }

        /// <summary>
        /// A resource list of creators who worked on this story.
        /// </summary>
        [JsonProperty("creators")]
        public CreatorList Creators 
        { 
            get 
            {
                return this.creators; 
            } 
            set 
            {
                this.creators = value;
                onPropertyChanged("Creators");
            }
        }

        /// <summary>
        /// A short description of the story.
        /// </summary>
        [JsonProperty("description")]
        public string Description 
        { 
            get 
            {
                return this.description; 
            } 
            set 
            {
                this.description = value;
                onPropertyChanged("Description");
            }
        }

        /// <summary>
        /// A resource list of the events in which this story appears.
        /// </summary>
        [JsonProperty("events")]
        public EventList Events 
        { 
            get 
            {
                return this.events; 
            } 
            set 
            {
                this.events = value;
                onPropertyChanged("Events");
            }
        }

        /// <summary>
        /// The unique ID of the story resource.
        /// </summary>
        [JsonProperty("id")]
        public int Id 
        { 
            get 
            {
                return this.id; 
            } 
            set 
            {
                this.id = value;
                onPropertyChanged("Id");
            }
        }

        /// <summary>
        /// The date the resource was most recently modified.
        /// </summary>
        [JsonProperty("modified")]
        public DateTime Modified 
        { 
            get 
            {
                return this.modified; 
            } 
            set 
            {
                this.modified = value;
                onPropertyChanged("Modified");
            }
        }

        /// <summary>
        /// A summary representation of the issue in which this story was originally published.
        /// </summary>
        [JsonProperty("originalissue")]
        public ComicSummary Originalissue 
        { 
            get 
            {
                return this.originalissue; 
            } 
            set 
            {
                this.originalissue = value;
                onPropertyChanged("Originalissue");
            }
        }

        /// <summary>
        /// The canonical URL identifier for this resource.
        /// </summary>
        [JsonProperty("resourceURI")]
        public string ResourceURI 
        { 
            get 
            {
                return this.resourceURI; 
            } 
            set 
            {
                this.resourceURI = value;
                onPropertyChanged("ResourceURI");
            }
        }

        /// <summary>
        /// A resource list containing series in which this story appears.
        /// </summary>
        [JsonProperty("series")]
        public SeriesList Series 
        { 
            get 
            {
                return this.series; 
            } 
            set 
            {
                this.series = value;
                onPropertyChanged("Series");
            }
        }

        /// <summary>
        /// The representative image for this story.
        /// </summary>
        [JsonProperty("thumbnail")]
        public Thumbnail Thumbnail 
        { 
            get 
            {
                return this.thumbnail; 
            } 
            set 
            {
                this.thumbnail = value;
                onPropertyChanged("Thumbnail");
            }
        }

        /// <summary>
        /// The story title.
        /// </summary>
        [JsonProperty("title")]
        public string Title 
        { 
            get 
            {
                return this.title; 
            } 
            set 
            {
                this.title = value;
                onPropertyChanged("Title");
            }
        }

        /// <summary>
        /// The story type e.g. interior story, cover, text story.
        /// </summary>
        [JsonProperty("type")]
        public string Type 
        { 
            get 
            {
                return this.type; 
            } 
            set 
            {
                this.type = value;
                onPropertyChanged("Type");
            }
        }

        /// <summary>
        /// Property changed event for observer pattern
        /// </summary>
        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Raises event when a property is changed
        /// </summary>
        /// <param name="propertyName">Name of the changed property</param>
        protected void onPropertyChanged(String propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
} 