/*
 * MarvelComics.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/12/2016
 */
using System;

namespace MarvelComics.PCL
{
    public partial class Configuration
    {
        //The base Uri for API calls
        public static string BaseUri = "http://gateway.marvel.com/v1/public";

        //TODO: Replace the Referer with an appropriate value
        public static string Referer = "TODO: Replace";

        //TODO: Replace the Apikey with an appropriate value
        public static string Apikey = "";

    }
}