/*
 * MarvelComics.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/12/2016
 */
using System;
using MarvelComics.PCL.Controllers;
using MarvelComics.PCL.Http.Client;

namespace MarvelComics.PCL
{
    public partial class MarvelComicsClient
    {

        /// <summary>
        /// Singleton access to Stories controller
        /// </summary>
        public StoriesController Stories
        {
            get
            {
                return MarvelComics.PCL.Controllers.StoriesController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to Series controller
        /// </summary>
        public SeriesController Series
        {
            get
            {
                return MarvelComics.PCL.Controllers.SeriesController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to Events controller
        /// </summary>
        public EventsController Events
        {
            get
            {
                return MarvelComics.PCL.Controllers.EventsController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to Creators controller
        /// </summary>
        public CreatorsController Creators
        {
            get
            {
                return MarvelComics.PCL.Controllers.CreatorsController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to Comics controller
        /// </summary>
        public ComicsController Comics
        {
            get
            {
                return MarvelComics.PCL.Controllers.ComicsController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to Characters controller
        /// </summary>
        public CharactersController Characters
        {
            get
            {
                return MarvelComics.PCL.Controllers.CharactersController.Instance;
            }
        }

        /// <summary>
        /// The shared http client to use for all API calls
        /// </summary>
        public IHttpClient SharedHttpClient
        {
            get
            {
                return BaseController.ClientInstance;
            }
            set
            {
                BaseController.ClientInstance = value;
            }        
        }
        
        /// <summary>
        /// Default constructor
        /// </summary>
        public MarvelComicsClient() { }

        /// <summary>
        /// Client initialization constructor
        /// </summary>
        public MarvelComicsClient(string referer, string apikey)
        {
            Configuration.Referer = referer;
            Configuration.Apikey = apikey;
        }
    }
}